// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkBlockApi.Data;

#nullable disable

namespace WorkBlockApi.Migrations
{
    [DbContext(typeof(WorkBlockContext))]
    [Migration("20230520013127_EmployeeEventMapNameId")]
    partial class EmployeeEventMapNameId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WorkBlockApi.Models.Administrator.Events.AdminAddedEventModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressFrom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdministratorAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdministratorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdministratorTaxId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashTransaction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("AdminAddedEvents");
                });

            modelBuilder.Entity("WorkBlockApi.Models.Administrator.Events.AdminUpdatedEventModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressFrom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdministratorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdministratorTaxId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashTransaction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NewAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("AdminUpdatedEvents");
                });

            modelBuilder.Entity("WorkBlockApi.Models.Employee.Events.EmployeeAddedEventModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressFrom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("EmployeeBegginingWorkDay")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("EmployeeEndWorkDay")
                        .HasColumnType("time(6)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeTaxId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashTransaction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeAddedEvents");
                });

            modelBuilder.Entity("WorkBlockApi.Models.Employee.Events.EmployeeUpdatedEventModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressFrom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("EmployeeBegginingWorkDay")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("EmployeeEndWorkDay")
                        .HasColumnType("time(6)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeTaxId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashTransaction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NewAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeUpdatedEvents");
                });

            modelBuilder.Entity("WorkBlockApi.Models.Employer.Events.EmployerAddedEventModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressFrom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerLegalAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerTaxId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashTransaction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("EmployerAddedEvents");
                });

            modelBuilder.Entity("WorkBlockApi.Models.Employer.Events.EmployerUpdatedEventModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressFrom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerLegalAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerTaxId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashTransaction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NewAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("EmployerUpdatedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
