// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkBlockApi.Data;

#nullable disable

namespace WorkBlockApi.Migrations
{
    [DbContext(typeof(WorkBlockContext))]
    [Migration("20230514192416_AdminAddedEvent")]
    partial class AdminAddedEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WorkBlockApi.Models.Administrator.Events.AdminAddedEventModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressFrom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdministratorAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdministratorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AdministratorTaxId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashTransaction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("AdminAddedEvents");
                });

#pragma warning restore 612, 618
        }
    }
}
